subscription:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhsso-operator.7.6.9-opr-002
realm:
  identityProviders:
    - alias: Gitlab
      providerId: oidc
      clientId: bf6e3bc4ac5cf8eb5be6d70401d511b7a3518061b863d928ce6454e6c2457113
      tokenUrl: https://gitlab-gitlab.apps.hub.jonkey.cc/oauth/token
      authorizationUrl: https://gitlab-gitlab.apps.hub.jonkey.cc/oauth/authorize
      clientAuthMethod: client_secret_basic
      syncMode: IMPORT
      clientSecret: "f87f03a64d839d4d9dd66bd3c902ba6211f410a2950269a5804ac7960fdf4e33"
client:
  redirectUri:
  - https://backstage-backstage.apps.hub.jonkey.cc/api/auth/oidc/handler/frame
