kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backstage-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
