apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage
  name: backstage
spec:
  clusterIP: None
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage-postgres
