apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage-postgres
  name: backstage-postgresql
spec:
  ports:
  - name: http
    port: 5432
    targetPort: http
  selector:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage-postgres
