apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: backstage-postgres
    app.kubernetes.io/version: v1.7.0
    helm.sh/chart: backstage-0.1.6
  name: backstage-postgresql
  namespace: backstageio
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5432
    targetPort: http
  selector:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage-postgres
