apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage
  name: backstage
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 4180
  selector:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage
